### ISSUE TITLE
+ControlNet

### ISSUE THREAD

**Issue by yosun** [FuturistAcoustics/EasyComputerVision#1]
Hello! Can you also add ControlNet local x-platform? 

I assume this works on all platforms - ios/android and webgl included?

**Comment by dilne** [comment]
Hi! Thank you for your interest.

We currently only offer a no-code interface for using image classification models (ResNet, ConvNeXt etc). It's on our roadmap to create an interface for using Stable Diffusion. Then we will see about implementing ControlNet. Apologies we don't have this functionality currently.

We use Unity's Sentis at the backend to run the models. As stated [here](https://unity.com/products/sentis), "Sentis works with all Unity-supported platforms, from mobile to PC to popular game consoles." If your platform is a Unity-supported platform, EasyComputerVision is also compatible.
